# Generated by Django 4.1.1 on 2024-06-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='picked_up_by',
            new_name='picked_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='dispatched_by',
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='dispatched_certificates',
            field=models.ManyToManyField(related_name='dispatched_records', to='b2.certificate'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='printed_certificates',
            field=models.ManyToManyField(related_name='printed_records', to='b2.certificate'),
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='b2.certificate')),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
