# Generated by Django 4.1.1 on 2024-06-29 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b2', '0005_certificaterecord_printed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='print_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='printed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
