# Generated by Django 4.1.1 on 2024-06-29 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b2', '0006_certificaterecord_print_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterecord',
            name='print_date',
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
