# Generated by Django 4.1.1 on 2024-06-30 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b2', '0007_remove_certificaterecord_print_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='print_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='dispatched_certificates',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='printed_certificates',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='certificate_number',
            field=models.CharField(max_length=50),
        ),
    ]
