# Generated by Django 4.1.1 on 2024-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0009_alter_dispatchrecord_certificate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='dispatched_certificates',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='dispatched_certificates',
            field=models.ManyToManyField(related_name='dispatched_daily_records', to='b2.certificaterecord'),
        ),
    ]
