# Generated by Django 4.1.1 on 2024-06-30 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b2', '0010_remove_dailyrecord_dispatched_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterecord',
            name='dispatch_phone',
        ),
        migrations.RemoveField(
            model_name='dispatchrecord',
            name='certificate_number',
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='dispatched_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='certificate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='b2.certificaterecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='certificate_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='dispatched_to',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='print_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
