# Generated by Django 4.1.1 on 2024-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0011_remove_certificaterecord_dispatch_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterecord',
            name='picked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
