# Generated by Django 4.1.1 on 2024-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0013_alter_certificaterecord_picked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='dispatched_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
