# Generated by Django 5.0.6 on 2024-07-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0014_dispatchrecord_dispatched_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CertificateFile', models.FileField(upload_to='certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='b2.certificaterecord')),
            ],
        ),
    ]
