# Generated by Django 4.2.7 on 2024-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0014_dispatchrecord_dispatched_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchrecord',
            name='dispatched_phone',
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='dispatched_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='picked_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
