# Generated by Django 5.0.6 on 2024-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0016_rename_certificatefile_certificates_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_number',
            field=models.CharField(max_length=100),
        ),
    ]
