# Generated by Django 5.0.6 on 2024-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0017_alter_certificates_certificate_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificates',
        ),
    ]
