# Generated by Django 5.0.6 on 2024-07-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0018_delete_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
