# Generated by Django 4.1.1 on 2024-07-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0018_certificaterecord_uploaded_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterecord',
            name='uploaded_file_path',
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='uploaded_certificate',
            field=models.FileField(blank=True, default='path/to/default_certificate.pdf', upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
