# Generated by Django 5.0.6 on 2024-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0019_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_file',
            field=models.FileField(upload_to='certificates/pdfs'),
        ),
    ]
