# Generated by Django 4.2.7 on 2024-07-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0019_certificaterecord_certificate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterecord',
            name='certificate_name',
        ),
    ]
