# Generated by Django 4.1.1 on 2024-07-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0019_remove_certificaterecord_uploaded_file_path_and_more'),
        ('b2', '0020_remove_certificaterecord_certificate_name'),
    ]

    operations = [
    ]
