# Generated by Django 4.1.1 on 2024-07-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0021_merge_20240709_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='uploaded_file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
