# Generated by Django 4.1.1 on 2024-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0025_certificaterecord_dispatched_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dispatched_certificates', models.ManyToManyField(blank=True, related_name='dispatched_daily_records', to='b2.certificaterecord')),
                ('printed_certificates', models.ManyToManyField(blank=True, related_name='printed_daily_records', to='b2.certificaterecord')),
            ],
        ),
    ]
