# Generated by Django 5.0.7 on 2024-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0026_dailyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterecord',
            name='uploaded_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
