# Generated by Django 5.0.7 on 2024-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0027_alter_certificaterecord_uploaded_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='dispatched_certificates',
            field=models.ManyToManyField(related_name='dispatched_daily_records', to='b2.certificaterecord'),
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='printed_certificates',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='printed_certificates',
            field=models.CharField(default='', max_length=255),
        ),
    ]
