# Generated by Django 5.0.7 on 2024-07-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0028_alter_dailyrecord_dispatched_certificates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchrecord',
            old_name='dispatch_phone',
            new_name='dispatched_phone',
        ),
    ]
