# Generated by Django 5.0.7 on 2024-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0029_rename_dispatch_phone_dispatchrecord_dispatched_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='dispatched_certificates',
            field=models.ManyToManyField(blank=True, related_name='dispatched_daily_records', to='b2.certificaterecord'),
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='printed_certificates',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='printed_certificates',
            field=models.ManyToManyField(blank=True, related_name='printed_daily_records', to='b2.certificaterecord'),
        ),
    ]
