# Generated by Django 4.1.1 on 2024-07-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0032_dispatchrecord_picked_by_wells_fargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='picked_by_wells_fargo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
