# Generated by Django 4.1.1 on 2024-07-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0033_certificaterecord_picked_by_wells_fargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrecord',
            name='picked_by_wells_fargo',
            field=models.BooleanField(default=False),
        ),
    ]
