# Generated by Django 4.1.1 on 2024-07-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0034_alter_dispatchrecord_picked_by_wells_fargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterecord',
            name='picked_by_wells_fargo',
        ),
        migrations.RemoveField(
            model_name='dispatchrecord',
            name='picked_by_wells_fargo',
        ),
    ]
