# Generated by Django 5.0.7 on 2024-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0035_remove_certificaterecord_picked_by_wells_fargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='picked_by_wells_fargo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
